trigger:
- main

name: Azure Pipelines
variables:
  python.version: '3.8.8'
stages:
- stage: Provisioning
  displayName: 'Provisioning'
  jobs:
  - job: provisioning
    displayName: 'Infrastracture Provisioning with Terraform'
    steps:
      - task: InstallSSHKey@0
        displayName: 'Install ssh-keys'
        inputs:
          knownHostsEntry: 'default'
          sshPublicKey: '$(PUBLIC_KEY)'
          sshKeySecureFile: 'id_rsa'
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Terraform Install'
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV2@2
        displayName: Terra Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1(87374ef2-5c69-4884-abed-6e7bb3294548)'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'tfstate16018'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
              
      - task: TerraformTaskV2@2
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'Azure subscription 1(87374ef2-5c69-4884-abed-6e7bb3294548)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
      - task: TerraformTaskV2@2
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'Azure subscription 1(87374ef2-5c69-4884-abed-6e7bb3294548)'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'

- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/drop-fakerestapi-$(Build.BuildId).zip'
    - publish: $(Build.ArtifactStagingDirectory)
      displayName: 'Upload FakeRestAPI'
      artifact: drop-fakerestapi
    - task: ArchiveFiles@2
      displayName: 'Archive Selenium tests'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-selenium-tests.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-selenium-tests.zip
      displayName: 'Upload Selenium Tests'
      artifact: drop-selenium