# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo terraform install start
  displayName: 'Run a one-line script'
- task: TerraformTaskV2@2
  displayName: Terra Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(87374ef2-5c69-4884-abed-6e7bb3294548)'
    backendAzureRmResourceGroupName: 'udacity-project3-rg'
    backendAzureRmStorageAccountName: 'tfstate16018'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- script: |
    echo the end.
  displayName: 'Run a multi-line script'
