trigger:
- main

name: Azure Pipelines
variables:
  python.version: '3.8.8'
stages:
- stage: Provisioning
  displayName: 'Provisioning'
  jobs:
  - job: provisioning
    displayName: 'Inrrastracture Provisioning with Terraform'
    steps:
      - task: InstallSSHKey@0
        displayName: 'Install ssh-keys'
        inputs:
          knownHostsEntry: 'default'
          sshKeySecureFile: 'id_rsa'
      - task: TerraformInstaller@0
        displayName: 'Install terraform'
        inputs:
          terraformVersion: '0.12.3'
      - task: TerraformTaskV2@2
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: '$(AZURE_SUBSCRIPTION_ID)'
          backendAzureRmResourceGroupName: 'udacity-project3-rg'
          backendAzureRmStorageAccountName: 'tfstate16018'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
      - task: TerraformTaskV1@0
        displayName: 'Terraform Plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: |
            -var "subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var "client_id=$(CLIENT_ID)" -var "client_secret=$(CLIENT_SECRET)" -var "tenant_id=$(TENANT_ID)" -var "public_key=$(PUBLIC_KEY)"
          environmentServiceNameAzureRM: 'tf-sys'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
      - task: TerraformTaskV1@0
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: |
            -var "subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var "client_id=$(CLIENT_ID)" -var "client_secret=$(CLIENT_SECRET)" -var "tenant_id=$(TENANT_ID)" -var "public_key=$(PUBLIC_KEY)"
          environmentServiceNameAzureRM: 'tf-sys'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'